### ISSUE TITLE
Issue: Add Documentation for Interpreter Pattern

### ISSUE THREAD

**Issue by BuketCulfaoglu** [BuketCulfaoglu/DesignPatterns#18]
**Description**:
We need to add comprehensive documentation for the Interpreter pattern in our repository. This documentation should explain the pattern, its participants, UML diagram, explanation of the code, use cases, and references for further reading.

**Tasks**:
Create a new markdown file named README.md in the BehavioralPatterns/InterpreterPattern directory.
Add README.md file

**Comment by ametFaciem** [comment]
Diagram should be included. Naming should be standart
