### ISSUE TITLE
Document Iterator Pattern

### ISSUE THREAD

**Issue by anti-pc** [BuketCulfaoglu/DesignPatterns#6]
**Description**:
Create detailed documentation for the Iterator pattern.
Include an explanation of the pattern, UML diagrams, and code examples.
Describe when to use the Iterator pattern and its advantages.

**Tasks**:
Write an overview of the Iterator pattern.
Create UML diagrams illustrating the pattern.
Provide code examples.
Document use cases and advantages.
Labels: documentation, design-pattern

**Comment by ametFaciem** [comment]
Nicely done 👍

**Comment by ametFaciem** [comment]
Nicely done 👍
